"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ERROR_CODES = void 0;
exports.ERROR_CODES = {
    // Authentication Errors
    AUTH_ERROR: 'AUTH_ERROR',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    INVALID_TOKEN: 'INVALID_TOKEN',
    UNAUTHORIZED: 'UNAUTHORIZED',
    // OTP Errors
    OTP_ERROR: 'OTP_ERROR',
    OTP_EXPIRED: 'OTP_EXPIRED',
    INVALID_OTP: 'INVALID_OTP',
    // Validation Errors
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INVALID_INPUT: 'INVALID_INPUT',
    // Database Errors
    DB_ERROR: 'DB_ERROR',
    RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
    DUPLICATE_RECORD: 'DUPLICATE_RECORD',
    // Event Errors
    EVENT_ERROR: 'EVENT_ERROR',
    EVENT_PUBLISH_ERROR: 'EVENT_PUBLISH_ERROR',
    EVENT_CONSUME_ERROR: 'EVENT_CONSUME_ERROR',
    // Service Errors
    SERVICE_ERROR: 'SERVICE_ERROR',
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
    // Rate Limiting
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
    // File Errors
    FILE_ERROR: 'FILE_ERROR',
    FILE_NOT_FOUND: 'FILE_NOT_FOUND',
    INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
    FILE_TOO_LARGE: 'FILE_TOO_LARGE',
    // Network Errors
    NETWORK_ERROR: 'NETWORK_ERROR',
    REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
    // System Errors
    SYSTEM_ERROR: 'SYSTEM_ERROR',
    UNKNOWN_ERROR: 'UNKNOWN_ERROR'
};
//# sourceMappingURL=error-codes.js.map